name: RiverCityRoasters
favicon: null
layout_spectrum: 0.24406
typography_spectrum: 0.09249
title: River City Roasters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5821f'
    - '#64666a'
    - '#ffffff'
    - '#a29fa2'
    - '#fbc89e'
  brandStrength: 0.3125
  lightness: 0.3265565587207675
  saturation: 0.9766263177152723
  rhythmicContrast: 0.6121780988760293
purpose: []
