name: RiverCityRoasters
favicon: null
layout_spectrum: 0.791268162894994
typography_spectrum: 0.5600473403465003
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7990197772160172
  lightness: 0.3265565587207675
  saturation: 0.9766263177152723
  rhythmicContrast: 0.6121780988760293
purpose: []
