name: RiverCityRoasters
favicon: null
layout_spectrum: 0.24406
typography_spectrum: 0.09249
title: River City Roasters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5821f'
    - '#64666a'
    - '#ffffff'
    - '#a29fa2'
    - '#fbc89e'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
